// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

Future<String> rustGreeting({required String name}) =>
    RustLib.instance.api.crateApiRustGreeting(name: name);

Future<List<String>> supportedAnnotationModes() =>
    RustLib.instance.api.crateApiSupportedAnnotationModes();
