// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `fmt`

Future<String> analyzeCam({required CamAnalysisRequest req}) =>
    RustLib.instance.api.crateApiCamAnalysisModAnalyzeCam(req: req);

class CamAnalysisRequest {
  final String pythonPath;
  final String modelPath;
  final String inputPath;
  final String outputDir;
  final double confThreshold;
  final double iouThreshold;
  final int imgsz;
  final String device;
  final String mode;
  final String smoothing;
  final int targetLayerIndex;
  final int targetClassId;

  const CamAnalysisRequest({
    required this.pythonPath,
    required this.modelPath,
    required this.inputPath,
    required this.outputDir,
    required this.confThreshold,
    required this.iouThreshold,
    required this.imgsz,
    required this.device,
    required this.mode,
    required this.smoothing,
    required this.targetLayerIndex,
    required this.targetClassId,
  });

  @override
  int get hashCode =>
      pythonPath.hashCode ^
      modelPath.hashCode ^
      inputPath.hashCode ^
      outputDir.hashCode ^
      confThreshold.hashCode ^
      iouThreshold.hashCode ^
      imgsz.hashCode ^
      device.hashCode ^
      mode.hashCode ^
      smoothing.hashCode ^
      targetLayerIndex.hashCode ^
      targetClassId.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is CamAnalysisRequest &&
          runtimeType == other.runtimeType &&
          pythonPath == other.pythonPath &&
          modelPath == other.modelPath &&
          inputPath == other.inputPath &&
          outputDir == other.outputDir &&
          confThreshold == other.confThreshold &&
          iouThreshold == other.iouThreshold &&
          imgsz == other.imgsz &&
          device == other.device &&
          mode == other.mode &&
          smoothing == other.smoothing &&
          targetLayerIndex == other.targetLayerIndex &&
          targetClassId == other.targetClassId;
}
