// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `broadcast_targets`, `broadcast_to_peers`, `join_host`, `json_bool_field`, `json_escape`, `json_object_or_string`, `json_raw_scalar`, `json_string_field`, `json_u16_field`, `json_u32_field`, `json_value_start`, `new`, `now_millis`, `ok_message`, `primary_local_ipv4`, `push_event`, `push_tcp_message`, `remove_host_client`, `required_json_string`, `run_client_reader`, `run_discovery_listener`, `run_host_broadcast`, `run_host_client_reader`, `run_tcp_host`, `send_to_host`, `send_to_peer`, `shutdown_stream`, `start_discovery`, `start_host`, `stop_all`, `stop_runtime`, `stop`, `write_json_line`
// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `ClientConfig`, `HostConfig`, `Runtime`

Future<String> commandJson({required String request}) =>
    RustLib.instance.api.crateApiCollaborationModCommandJson(request: request);

Future<String> pollEventsJson({required BigInt maxEvents}) => RustLib
    .instance
    .api
    .crateApiCollaborationModPollEventsJson(maxEvents: maxEvents);
