// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `build_training_script`, `compute_elapsed_seconds`, `read_last_csv_line`, `read_results_csv_columns`, `verify_python`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `clone`, `fmt`, `fmt`

Future<String> startTraining({required TrainingConfig config}) =>
    RustLib.instance.api.crateApiTrainingModStartTraining(config: config);

Future<TrainingProgress?> pollTrainingProgress() =>
    RustLib.instance.api.crateApiTrainingModPollTrainingProgress();

Future<String> stopTraining() =>
    RustLib.instance.api.crateApiTrainingModStopTraining();

class TrainingConfig {
  final String pythonPath;
  final String modelPath;
  final String dataYamlPath;
  final String projectDir;
  final String experimentName;
  final int epochs;
  final int imgsz;
  final String batch;
  final String device;
  final double lr0;
  final double momentum;
  final double hsvS;
  final double hsvV;
  final double translate;
  final double scale;
  final double shear;
  final double flipud;
  final double fliplr;
  final double degrees;
  final int workers;
  final bool amp;
  final bool resume;
  final double clsPw;

  const TrainingConfig({
    required this.pythonPath,
    required this.modelPath,
    required this.dataYamlPath,
    required this.projectDir,
    required this.experimentName,
    required this.epochs,
    required this.imgsz,
    required this.batch,
    required this.device,
    required this.lr0,
    required this.momentum,
    required this.hsvS,
    required this.hsvV,
    required this.translate,
    required this.scale,
    required this.shear,
    required this.flipud,
    required this.fliplr,
    required this.degrees,
    required this.workers,
    required this.amp,
    required this.resume,
    required this.clsPw,
  });

  @override
  int get hashCode =>
      pythonPath.hashCode ^
      modelPath.hashCode ^
      dataYamlPath.hashCode ^
      projectDir.hashCode ^
      experimentName.hashCode ^
      epochs.hashCode ^
      imgsz.hashCode ^
      batch.hashCode ^
      device.hashCode ^
      lr0.hashCode ^
      momentum.hashCode ^
      hsvS.hashCode ^
      hsvV.hashCode ^
      translate.hashCode ^
      scale.hashCode ^
      shear.hashCode ^
      flipud.hashCode ^
      fliplr.hashCode ^
      degrees.hashCode ^
      workers.hashCode ^
      amp.hashCode ^
      resume.hashCode ^
      clsPw.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is TrainingConfig &&
          runtimeType == other.runtimeType &&
          pythonPath == other.pythonPath &&
          modelPath == other.modelPath &&
          dataYamlPath == other.dataYamlPath &&
          projectDir == other.projectDir &&
          experimentName == other.experimentName &&
          epochs == other.epochs &&
          imgsz == other.imgsz &&
          batch == other.batch &&
          device == other.device &&
          lr0 == other.lr0 &&
          momentum == other.momentum &&
          hsvS == other.hsvS &&
          hsvV == other.hsvV &&
          translate == other.translate &&
          scale == other.scale &&
          shear == other.shear &&
          flipud == other.flipud &&
          fliplr == other.fliplr &&
          degrees == other.degrees &&
          workers == other.workers &&
          amp == other.amp &&
          resume == other.resume &&
          clsPw == other.clsPw;
}

class TrainingProgress {
  final int currentEpoch;
  final int totalEpochs;
  final String status;
  final double? trainLoss;
  final double? valLoss;
  final double? map50;
  final double? map5095;
  final double? precision;
  final double? recall;
  final double? lr;
  final double elapsedSeconds;
  final double estimatedRemainingSeconds;

  const TrainingProgress({
    required this.currentEpoch,
    required this.totalEpochs,
    required this.status,
    this.trainLoss,
    this.valLoss,
    this.map50,
    this.map5095,
    this.precision,
    this.recall,
    this.lr,
    required this.elapsedSeconds,
    required this.estimatedRemainingSeconds,
  });

  @override
  int get hashCode =>
      currentEpoch.hashCode ^
      totalEpochs.hashCode ^
      status.hashCode ^
      trainLoss.hashCode ^
      valLoss.hashCode ^
      map50.hashCode ^
      map5095.hashCode ^
      precision.hashCode ^
      recall.hashCode ^
      lr.hashCode ^
      elapsedSeconds.hashCode ^
      estimatedRemainingSeconds.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is TrainingProgress &&
          runtimeType == other.runtimeType &&
          currentEpoch == other.currentEpoch &&
          totalEpochs == other.totalEpochs &&
          status == other.status &&
          trainLoss == other.trainLoss &&
          valLoss == other.valLoss &&
          map50 == other.map50 &&
          map5095 == other.map5095 &&
          precision == other.precision &&
          recall == other.recall &&
          lr == other.lr &&
          elapsedSeconds == other.elapsedSeconds &&
          estimatedRemainingSeconds == other.estimatedRemainingSeconds;
}
