pub mod api;

// Generated by flutter_rust_bridge. Keep this module private and regenerate it
// with `flutter_rust_bridge_codegen generate --config-file flutter_rust_bridge.yaml`.
mod frb_generated;
